language: python
python:
  - 2.7
script: make test
notifications:
  email: false
env:
  matrix:
    - DJANGO='django~=1.6.0'
    - DJANGO='django~=1.7.0'
    - DJANGO='django~=1.8.0'
    - DJANGO='django~=1.9.0'
install:
  - pip install $DJANGO
  - psql -c 'CREATE DATABASE django_form_models' -U postgres;
  - pip install -r test_requirements.txt
  - pip install -e .
