language: python
python:
  - 2.6
  - 2.7
script: make test
notifications:
  email: false
install:
  - psql -c 'CREATE DATABASE django_form_models' -U postgres;
  - pip install -r test_requirements.txt
  - pip install .
