language: python
python:
  - 2.7
script: make test
notifications:
  email: false
env:
  matrix:
    - DJANGO='django>=1.4,<1.5'
    - DJANGO='django>=1.5,<1.6'
    - DJANGO='django>=1.6,<1.7'
install:
  - psql -c 'CREATE DATABASE django_form_models' -U postgres;
  - pip install -r test_requirements.txt
  - pip install .
